carte_refuge:
    resource: "@CarteRefugeBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site_public_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

rembourse:
    path:     /rembourse
    defaults: { _controller: RembourseBundle:Default:index}

