# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
      #  mainprovider:
      #   entity: { class: UserBundle:User, property: username }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
            logout:
              path:       fos_user_security_logout
              target:     /
            logout: true
            anonymous:  true
            remember_me:
                secret:     %secret%

    access_control:
        - { path: ^/profile/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


